name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 4. Rodar ESLint para checar o código
      - name: Run ESLint
        run: npm run lint

      # 5. Rodar Prettier para formatar o código
      - name: Run Prettier
        run: npm run format

      # 6. Fazer o build do projeto
      - name: Build project
        run: npm run build
