name: Deploy Vite to GitHub Pages

on:
  # Executa o workflow em pushes para a branch main
  push:
    branches:
      - main

  # Permite executar manualmente
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 4. Corrigir permissões do Vite
      - name: Fix permissions for Node.js binaries
        run: chmod +x ./node_modules/.bin/vite

      # 5. Build do projeto com Vite
      - name: Build project
        run: npm run build

      # 6. Fazer upload do build como artifact para o job de deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  # Job de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 1. Fazer deploy do conteúdo para o GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
